@isTest
public class simplegetsetTest{

    public static testMethod void testMyClass(){
       //Test.startTest();           
       simplegetset controller = new simplegetset();
       controller.userinput= 'ash';
       //PageReference pg = Page.GetSetExample;
       //Test.setCurrentPage(pg); 
       //System.debug('You have entered the input string --> '+controller1.userinput);
       //Test.stopTest();
        

        }
}